Repository logisim-evolution/logisim-evolution, pull requests merged in 2021-09, with the labels that each got.

#957 Bumps JDK to v16
  .github/workflows/build.yml
  .github/workflows/nightly.yml
  build.gradle.kts
  docs/developers.md
Labels: dependent

#973 libraryRemove() refactoring
  src/main/java/com/cburch/gray/Components.java
  src/main/java/com/cburch/logisim/soc/Soc.java
  src/main/java/com/cburch/logisim/std/Builtin.java
  src/main/java/com/cburch/logisim/std/arith/ArithmeticLibrary.java
  src/main/java/com/cburch/logisim/std/base/BaseLibrary.java
  src/main/java/com/cburch/logisim/std/bfh/BfhLibrary.java
  src/main/java/com/cburch/logisim/std/gates/GatesLibrary.java
  src/main/java/com/cburch/logisim/std/hdl/HdlLibrary.java
  src/main/java/com/cburch/logisim/std/io/IoLibrary.java
  src/main/java/com/cburch/logisim/std/io/extra/ExtraIoLibrary.java
  src/main/java/com/cburch/logisim/std/memory/MemoryLibrary.java
  src/main/java/com/cburch/logisim/std/plexers/PlexersLibrary.java
  src/main/java/com/cburch/logisim/std/tcl/TclLibrary.java
  src/main/java/com/cburch/logisim/std/ttl/TtlLibrary.java
  src/main/java/com/cburch/logisim/std/wiring/WiringLibrary.java
  src/main/java/com/cburch/logisim/tools/Library.java
Labels: dependent

#977 Removed "dead" analyze option and references to the seperate "tracked" version
  src/main/java/com/cburch/logisim/Main.java
  src/main/java/com/cburch/logisim/file/XmlCircuitReader.java
  src/main/java/com/cburch/logisim/file/XmlReader.java
  src/main/java/com/cburch/logisim/gui/menu/MainMenuListener.java
  src/main/java/com/cburch/logisim/gui/menu/MenuProject.java
  src/main/java/com/cburch/logisim/gui/menu/Popups.java
  src/main/java/com/cburch/logisim/gui/menu/WindowManagers.java
  src/main/java/com/cburch/logisim/gui/prefs/SimOptions.java
  src/main/java/com/cburch/logisim/gui/start/Startup.java
  src/main/resources/resources/logisim/strings/gui/gui.properties
  src/main/resources/resources/logisim/strings/gui/gui_de.properties
  src/main/resources/resources/logisim/strings/gui/gui_el.properties
  src/main/resources/resources/logisim/strings/gui/gui_es.properties
  src/main/resources/resources/logisim/strings/gui/gui_fr.properties
  src/main/resources/resources/logisim/strings/gui/gui_it.properties
  src/main/resources/resources/logisim/strings/gui/gui_ja.properties
  src/main/resources/resources/logisim/strings/gui/gui_nl.properties
  src/main/resources/resources/logisim/strings/gui/gui_pl.properties
  src/main/resources/resources/logisim/strings/gui/gui_pt.properties
  src/main/resources/resources/logisim/strings/gui/gui_ru.properties
Labels: dependent

#1066 Updated artwork/assets update process docs
  artwork/README.md
Labels: documentation

#1115 Removed CRLF check from checkstyle worker.
  .github/workflows/checkstyle.yml
Labels: pri +1
